

define void @proc_cast_int_to_int() { ret void }
define void @proc_cast_int_to_ptr() { ret void }
define void @proc_cast_int_to_str() { ret void }
define void @proc_cast_ptr_to_int() { ret void }
define void @proc_cast_ptr_to_ptr() { ret void }
define void @proc_cast_ptr_to_str() { ret void }
define void @proc_cast_str_to_int() { ret void }
define void @proc_cast_str_to_ptr() { ret void }
define void @proc_cast_str_to_str() { ret void }

define void @proc_cast_int_int_to_int_int() { ret void }
define void @proc_cast_int_int_to_int_ptr() { ret void }
define void @proc_cast_int_int_to_int_str() { ret void }
define void @proc_cast_int_int_to_ptr_int() { ret void }
define void @proc_cast_int_int_to_ptr_ptr() { ret void }
define void @proc_cast_int_int_to_ptr_str() { ret void }
define void @proc_cast_int_int_to_str_int() { ret void }
define void @proc_cast_int_int_to_str_ptr() { ret void }
define void @proc_cast_int_int_to_str_str() { ret void }
define void @proc_cast_int_ptr_to_int_int() { ret void }
define void @proc_cast_int_ptr_to_int_ptr() { ret void }
define void @proc_cast_int_ptr_to_int_str() { ret void }
define void @proc_cast_int_ptr_to_ptr_int() { ret void }
define void @proc_cast_int_ptr_to_ptr_ptr() { ret void }
define void @proc_cast_int_ptr_to_ptr_str() { ret void }
define void @proc_cast_int_ptr_to_str_int() { ret void }
define void @proc_cast_int_ptr_to_str_ptr() { ret void }
define void @proc_cast_int_ptr_to_str_str() { ret void }
define void @proc_cast_int_str_to_int_int() { ret void }
define void @proc_cast_int_str_to_int_ptr() { ret void }
define void @proc_cast_int_str_to_int_str() { ret void }
define void @proc_cast_int_str_to_ptr_int() { ret void }
define void @proc_cast_int_str_to_ptr_ptr() { ret void }
define void @proc_cast_int_str_to_ptr_str() { ret void }
define void @proc_cast_int_str_to_str_int() { ret void }
define void @proc_cast_int_str_to_str_ptr() { ret void }
define void @proc_cast_int_str_to_str_str() { ret void }
define void @proc_cast_ptr_int_to_int_int() { ret void }
define void @proc_cast_ptr_int_to_int_ptr() { ret void }
define void @proc_cast_ptr_int_to_int_str() { ret void }
define void @proc_cast_ptr_int_to_ptr_int() { ret void }
define void @proc_cast_ptr_int_to_ptr_ptr() { ret void }
define void @proc_cast_ptr_int_to_ptr_str() { ret void }
define void @proc_cast_ptr_int_to_str_int() { ret void }
define void @proc_cast_ptr_int_to_str_ptr() { ret void }
define void @proc_cast_ptr_int_to_str_str() { ret void }
define void @proc_cast_ptr_ptr_to_int_int() { ret void }
define void @proc_cast_ptr_ptr_to_int_ptr() { ret void }
define void @proc_cast_ptr_ptr_to_int_str() { ret void }
define void @proc_cast_ptr_ptr_to_ptr_int() { ret void }
define void @proc_cast_ptr_ptr_to_ptr_ptr() { ret void }
define void @proc_cast_ptr_ptr_to_ptr_str() { ret void }
define void @proc_cast_ptr_ptr_to_str_int() { ret void }
define void @proc_cast_ptr_ptr_to_str_ptr() { ret void }
define void @proc_cast_ptr_ptr_to_str_str() { ret void }
define void @proc_cast_ptr_str_to_int_int() { ret void }
define void @proc_cast_ptr_str_to_int_ptr() { ret void }
define void @proc_cast_ptr_str_to_int_str() { ret void }
define void @proc_cast_ptr_str_to_ptr_int() { ret void }
define void @proc_cast_ptr_str_to_ptr_ptr() { ret void }
define void @proc_cast_ptr_str_to_ptr_str() { ret void }
define void @proc_cast_ptr_str_to_str_int() { ret void }
define void @proc_cast_ptr_str_to_str_ptr() { ret void }
define void @proc_cast_ptr_str_to_str_str() { ret void }
define void @proc_cast_str_int_to_int_int() { ret void }
define void @proc_cast_str_int_to_int_ptr() { ret void }
define void @proc_cast_str_int_to_int_str() { ret void }
define void @proc_cast_str_int_to_ptr_int() { ret void }
define void @proc_cast_str_int_to_ptr_ptr() { ret void }
define void @proc_cast_str_int_to_ptr_str() { ret void }
define void @proc_cast_str_int_to_str_int() { ret void }
define void @proc_cast_str_int_to_str_ptr() { ret void }
define void @proc_cast_str_int_to_str_str() { ret void }
define void @proc_cast_str_ptr_to_int_int() { ret void }
define void @proc_cast_str_ptr_to_int_ptr() { ret void }
define void @proc_cast_str_ptr_to_int_str() { ret void }
define void @proc_cast_str_ptr_to_ptr_int() { ret void }
define void @proc_cast_str_ptr_to_ptr_ptr() { ret void }
define void @proc_cast_str_ptr_to_ptr_str() { ret void }
define void @proc_cast_str_ptr_to_str_int() { ret void }
define void @proc_cast_str_ptr_to_str_ptr() { ret void }
define void @proc_cast_str_ptr_to_str_str() { ret void }
define void @proc_cast_str_str_to_int_int() { ret void }
define void @proc_cast_str_str_to_int_ptr() { ret void }
define void @proc_cast_str_str_to_int_str() { ret void }
define void @proc_cast_str_str_to_ptr_int() { ret void }
define void @proc_cast_str_str_to_ptr_ptr() { ret void }
define void @proc_cast_str_str_to_ptr_str() { ret void }
define void @proc_cast_str_str_to_str_int() { ret void }
define void @proc_cast_str_str_to_str_ptr() { ret void }
define void @proc_cast_str_str_to_str_str() { ret void }
